extends:
  - stylelint-config-recommended
  - stylelint-config-recommended-scss
plugins:
  - stylelint-scss
ignoreFiles:
  - '**/*.html'
  - '**/*.njk'
rules:
  string-quotes: single
  scss/at-rule-no-unknown: null
  scss/at-import-no-partial-leading-underscore: null
