parser: '@babel/eslint-parser'
env:
  browser: true
  commonjs: false
  es6: true
  node: false
extends:
  - 'eslint:recommended'
  - 'plugin:compat/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-unused-vars: warn
  semi: warn
  no-console: warn
